traffic_sign_classes = [
    "Speed Limit 20",
    "Speed Limit 30",
    "Speed Limit 50",
    "Speed Limit 60",
    "Speed Limit 70",
    "Speed Limit 80",
    "End of Speed Limit 80",
    "Speed Limit 100",
    "Speed Limit 120",
    "No Entry",
    "One Way",
    "No U-Turn",
    "No Right Turn",
    "No Left Turn",
    "Stop",
    "Yield",
    "Crosswalk",
    "Traffic Signal",
    "Pedestrian",
    "Bicycle Lane",
    "Parking",
    "No Parking",
    "No Stopping",
    "School Zone",
    "Construction Zone",
    "Slippery Road",
    "Danger",
    "Wild Animals",
    "Road Work",
    "Right Turn Only",
    "Left Turn Only",
    "Straight Only",
    "Roundabout",
    "Information",
    "Hospital",
    "Fuel Station",
    "Rest Area",
    "Warning Sign",
    "Railway Crossing",
    "Low Bridge",
    "Weight Limit",
    "Height Limit",
    "Width Limit",
    "Bump",
    "Road Closed",
    "End of All Restrictions",
    "Detour",
    "Traffic Jam",
    "No Bicycles",
    "No Pedestrians"
]
